### ISSUE TITLE
Website Purchases Pixel Not Showing Sales?

### ISSUE THREAD

**Issue by andaydvice** [magestat/magento2-facebook-pixel#10]
We have added the pixel code below that is for tracking website purchases for Facebook Ads

Website: https://www.tigress.com.au

Its confirmed that the dynamic pricing is working as expected, however there is no actual sales value being shown in the Facebook ads dashboard (Restricted access so that cannot be shown currently).

This is the thank-you page pixel information:

https://drive.google.com/file/d/1I9fwP_knrRd-BMPuZXugrcHaeI7k2Vk1/view

This is the thank-you page code:

https://docs.google.com/document/d/1vL5bFHR-raUX6h9Y9c9psYtEPV4DPrgGASedKZ9BmYU/edit

--------------------
Website Pixel code for tracking website purchases:

<script type="text/x-magento-init">
{
    "*": {
        "Magestat_FacebookPixel/js/pixel-code": {
            "isCookieEnabled": 0,
            "currentWebsite": 1,
            "pixelCode": "880232132408668",
            "storeCurrency": "AUD",
            "cookieName": "user_allowed_save_cookie"
        }
    }
}
</script>

<script type="text/x-magento-init">
{
    "*": {
        "Magestat_FacebookPixel/js/actions/success": {
            "currency": "AUD",
            "contents": [{"id":"PQ245W-NW","name":"\"Monaco\" Hampton Style Pedestal Recycled Elm Timber Dining Table Natural with White Base 245cmW x 105cmD  x 77cmH","item_price":2199,"quantity":1}],
            "contentIds": ["PQ245W-NW"],
            "total": "2398"
        }
    }
}
</script>

---------------------------

> Magento version. 2.3.3 
> Edition: Magento Commerce 

----------------------------

Configuration settings

https://drive.google.com/file/d/1UUZfVnDpObu1FlSxRUXH38-GCdHS-nXF/view

-------------------------

Date of install:

>It's 23/06/2020
>Version: 1.0.5

--------------------------

 - OS: macOS Catalina 10.15.6
 - Browser Brave
 - Version 1.10.95 Chromium: 83.0.4103.106 (Official Build) (64-bit)

----------------------------------------

**Comment by williankeller** [comment]
Thanks for your message @andaydvice.
Could you send us a screenshot with the Purchase dropdown opened? So, we can see what's wrong with the data push.

**Comment by williankeller** [comment]
I'm closing the issue as no further feedback from the author was provided.
