### ISSUE TITLE
Store view option is not available

### ISSUE THREAD

**Issue by shinesoftware** [magestat/magento2-facebook-pixel#11]
Hello guys,

when we try to setup the extension for a specific store view in the Store > Configuration > Magestat > Pixel this one disappear!

Can you help us to solve this issue?

thanks

**Comment by shinesoftware** [comment]
Up

**Comment by williankeller** [comment]
Hi @shinesoftware!
Thanks for your message, The module is configurable to work only within websites.
What exactly are you trying to achieve by setting at the store level?

**Comment by mturillo** [comment]
Hi @williankeller thanks for the reply. We have a multistore with a multidomain configuration and we have noticed that Facebook reads all the selling goods of all stores. We'd like to handle with Facebook just one store. How have we have to achieve it? thanks

**Comment by mturillo** [comment]
Up

**Comment by williankeller** [comment]
Thank you all for the patience, it will be released in the next version 1.0.7.

I'll close this one as the release is being tracked under the issue #16
