### ISSUE TITLE
Option dropdown that controls tax isn't informative

### ISSUE THREAD

**Issue by erfanimani** [magestat/magento2-facebook-pixel#12]
It simply says Settings — Enabled (store/config), no indication that this is actually controlling whether price tracking includes tax or not.

**Comment by williankeller** [comment]
Hi @erfanimani, what's your suggestion here?

**Comment by erfanimani** [comment]
See PR here: https://github.com/magestat/magento2-facebook-pixel/pull/14

Changed "Enabled" to "Include tax", and added comment. (The enabled label must have been copy/paste leftover)
