### ISSUE TITLE
HTML validation error

### ISSUE THREAD

**Issue by erfanimani** [magestat/magento2-facebook-pixel#15]
An `img` tag appears in a `noscript` tag within `<head>`. Image tags can't appear within the document head.

Moreover, the entirety of `pixel-code.phtml` could be moved to the body, or before-body-end container, as I believe the RequireJS javascript only kicks in after the whole page is loaded anyway. For scripts initialized with `"text/x-magento-init"` it shouldn't make a difference whether it's located in the head, or body.

Are you happy for me to create a PR @williankeller ?

**Comment by williankeller** [comment]
Hi @erfanimani, it would be great if you help us out here! It would be much appreciated!
