### ISSUE TITLE
obsolete function

### ISSUE THREAD

**Issue by nadiamedraghfree** [magestat/magento2-facebook-pixel#2]
hello,

i have an error when i enable this module,
because the  function roundPrice in  magestat/module-facebook-pixel/Block/AbstractPixel.php line 153 is depreciate
i replace roundPrice by convertAndRound , and it's work verry good

**Comment by williankeller** [comment]
Hi @nadiamedraghfree
Could you share more details about your Magento version and PHP version?
Currently, we have this module running at 2.3.1 and we don't have any issues.

**Comment by nadiamedraghfree** [comment]
Hi @williankeller 
Magento ver. 2.2.8
PHP 7.1.22

**Comment by nadiamedraghfree** [comment]
roundPrice is missing in my magento project

**Comment by williankeller** [comment]
So, it isn't an obsolete function, your Magento version isn't compatible with this extension.
Good you have found your solution ;).

**Comment by Thomas-Papiernik-Insign** [comment]
Hi @williankeller , using round is better because is working in all magento2 version.
roundPrice and round are almost the same :
    public function round($price)
    {
        return round($price, 2);
    }
    /**
     * Round price with precision
     *
     * @param float $price
     * @param int $precision
     * @return float
     */
    public function roundPrice($price, $precision = self::DEFAULT_PRECISION)
    {
        return round($price, $precision);
    }

1+ to use round

**Comment by williankeller** [comment]
Hi @nadiamedraghfree, @Thomas-Papiernik-Insign
The `round` method is deprecated since 2.3.0
https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/Pricing/PriceCurrencyInterface.php#L82

**Comment by Thomas-Papiernik-Insign** [comment]
You are right. We try with convertAndRound (who is not deprecated). This should be better because convertAndRound use the current currency and convert the value to this currency.

**Comment by carloricci84** [comment]
I created a patch for people that are still in 2.2 if anybody is interested :

--- ./vendor/magestat/module-facebook-pixel/Block/AbstractPixel.php	2019-07-08 15:46:06.000000000 -0400
+++ ./vendor/magestat/module-facebook-pixel/Block/AbstractPixel.php	2019-07-08 15:44:54.000000000 -0400
@@ -150,7 +150,7 @@
      */
     public function formatPrice($amount)
     {
-        return $this->price->roundPrice($amount);
+        return $this->price->convertAndRound($amount);
     }
 
     /**
