### ISSUE TITLE
Composer version still use 1.0.2 which is incompatible with PHP 7.3.x

### ISSUE THREAD

**Issue by grll** [magestat/magento2-facebook-pixel#4]
**Describe the bug**
Running `bin/composer require magestat/module-facebook-pixel` on PHP 7.3 and above will cause:

[InvalidArgumentException]                                                                               
  Could not find package magestat/module-facebook-pixel in any version matching your PHP version (7.3.13)  

as it is downloading from tag 1.0.2 which limit PHP to PHP 7.2.x

**Comment by williankeller** [comment]
Hi @grll,
Thank you for bringing this issue. Probably it was a mismatch from the data source to the Packagist (our composer manager).
It looks like it's working as expected now. Please try it out and let us know if you have any issues.

```bash
composer require magestat/module-facebook-pixel
```

**Comment by williankeller** [comment]
@grll,
Don't forget to give us a star ;D
