### ISSUE TITLE
Uncaught Error: Call to undefined method PriceCurrency::roundPrice when viewing Product Page.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magestat/magento2-facebook-pixel#7]
**Describe the bug**

**To Reproduce**
Install module, and enable, but not marked as enabled in Magento Admin Settings.
View product page.

**Expected behavior**
Product page should load.

```
{
    "*": {
        "Magestat_FacebookPixel/js/actions/product": {
            "currency": "NZD",
            "contents": <br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined method Magento\Directory\Model\PriceCurrency::roundPrice() in /var/www/html/app/code/Magestat/FacebookPixel/Block/AbstractPixel.php:145
Stack trace:
#0 /var/www/html/app/code/Magestat/FacebookPixel/Block/Product.php(74): Magestat\FacebookPixel\Block\AbstractPixel-&gt;formatPrice(14.99)
#1 /var/www/html/app/code/Magestat/FacebookPixel/view/frontend/templates/actions/product.phtml(9): Magestat\FacebookPixel\Block\Product-&gt;getCurrentProduct()
#2 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/a...')
#3 /var/www/html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php-&gt;render(Object(Magestat\FacebookPixel\Block\Product), '/var/www/html/a...', Array)
#4 /var/www/html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template-&gt;fetchView('/var/www/html/a...')
#5 /var/www/html/app/code/Magestat/FacebookPixel/Block/AbstractPixel.php(81): Magento\Framework\Vi in <b>/var/www/html/app/code/Magestat/FacebookPixel/Block/AbstractPixel.php</b> on line <b>145</b><br />
```

**Comment by LiamKarlMitchell** [comment]
Looks like its expected to just use ```round()```

```php
    /**
     * @param $amount
     * @return float
     */
    public function formatPrice($amount)
    {
        return $this->price->round($amount);
    }
```

**Comment by williankeller** [comment]
Hi, @LiamKarlMitchell.
Thank you for letting us know about this issue and the contribution you've made.
We've generated a new release version: [Tag 1.0.5](https://github.com/magestat/magento2-facebook-pixel/releases/tag/1.0.5). You can also get it as a composer version: [Package 1.0.5](https://packagist.org/packages/magestat/module-facebook-pixel#1.0.5).

However, it's important to mention this method is deprecated in the newest Magento versions.
You can check it here: https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/Pricing/PriceCurrencyInterface.php#L86
With that said, we have to revisit this issue in the future, just to make sure the extension will work with the new versions as well.

In meanwhile, can you give this extension a STAR? This helps us to get more visibility.
Thank you!

**Comment by LiamKarlMitchell** [comment]
What do they intend for us to use in the future (convertAndRound)? I have other plugins that may also using round and also they need to take Special Price into consideration.

Also the plugin was Disabled in the settings when this issue happened, so its block should not have been running code.

I don't use composer it is to slow :( just installing into app/code is easier.

Did you publish the project to Magento Marketplace?
https://marketplace.magento.com/catalogsearch/result/?q=Facebook%20Pixel
